- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt
      command: sudo apt-get update

    - name: Install Docker
      command: sudo apt-get install -y docker.io

    - name: Start Docker Service
      command: sudo systemctl start docker

    - name: Stop existing FinanceMe container (if running)
      command: docker stop financeme-container
      ignore_errors: yes

    - name: Remove existing FinanceMe container (if exists)
      command: docker rm financeme-container
      ignore_errors: yes

    - name: Free port 8081 if used
      shell: |
        {% raw %}
        CONTAINER_ID=$(docker ps --filter "publish=8081" --format "{{.ID}}")
        if [ -n "$CONTAINER_ID" ]; then
          docker rm -f $CONTAINER_ID
        fi
        {% endraw %}
      ignore_errors: yes

    - name: Deploy FinanceMe Container
      command: docker run -d --name financeme-container -p 8081:8081 ramachandrampm/financeme-image:latest
